# Generated by Django 3.2.7 on 2021-09-11 15:35

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations

class Migration(migrations.Migration):

   
dependencies = [
        ('blog', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resumo',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
